//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAIT2113_Web_Application_Development
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int Order_ID { get; set; }
        public int Art_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> PriceEach { get; set; }
        public string Status { get; set; }
    
        public virtual Artwork Artwork { get; set; }
        public virtual Order Order { get; set; }
    }
}
